/**
 * Generator (ADR-004): emit the VSCode editor artifacts **from the canonical package** (`@attack/rule-schema`)
 * + the live engine response registry, so they can't drift from the engine.
 *
 *   node --import tsx/esm tools/gen-rule-schema.ts            # write the generated files
 *   node --import tsx/esm tools/gen-rule-schema.ts --check    # exit 1 if any committed file is stale
 *
 * `buildTargets()` is pure (no I/O) so the drift-guard test (`schema-drift.test.ts`) can compare it to disk;
 * the CLI runs only when this file is executed directly.
 */
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildRuleJsonSchema } from '@attack/rule-schema';
import { RESPONSE_IDS } from '0x13d-attack-rules-community';

const here = dirname(fileURLToPath(import.meta.url));

export interface GenTarget {
  path: string;
  content: string;
}

/** The generated artifacts, each derived from the canonical package + the live engine response registry. */
export function buildTargets(): GenTarget[] {
  const ids = [...RESPONSE_IDS];
  return [
    {
      path: join(here, '..', '..', 'vscode', 'schemas', 'attack-rule.schema.json'),
      content: JSON.stringify(buildRuleJsonSchema(ids), null, 2) + '\n',
    },
    {
      path: join(here, '..', '..', 'vscode', 'src', 'responseIds.generated.ts'),
      content:
        '// GENERATED by src/tools/gen-rule-schema.ts (ADR-004) — do not edit. The valid response ids, derived\n' +
        '// from the engine response registry (buildResponseRegistry); VSCode passes them to the shared validator.\n' +
        `export const RESPONSE_IDS: readonly string[] = ${JSON.stringify(ids)};\n`,
    },
  ];
}

function runCli(): void {
  const check = process.argv.includes('--check');
  let stale = false;
  for (const { path, content } of buildTargets()) {
    if (check) {
      const current = existsSync(path) ? readFileSync(path, 'utf8') : '';
      if (current !== content) {
        console.error(`[gen-rule-schema] OUT OF SYNC — ${path} is stale. Run \`npm run gen:schema\`.`);
        stale = true;
      }
    } else {
      writeFileSync(path, content);
      console.log(`[gen-rule-schema] wrote ${path}`);
    }
  }
  if (check && stale) process.exit(1);
  if (check) console.log(`[gen-rule-schema] in sync (responses: ${[...RESPONSE_IDS].join(', ')}).`);
}

// Run as a CLI only when executed directly — not when imported by the drift-guard test.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) runCli();
