// GENERATED by src/tools/gen-rule-schema.ts (ADR-004) — do not edit. The valid response ids, derived
// from the engine response registry (buildResponseRegistry); VSCode passes them to the shared validator.
export const RESPONSE_IDS: readonly string[] = ["alert","disableExtension","closeTab","removeCookie","cancelDownload"];
